service: jest-runner
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024
  timeout: 30
functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: helloTest
          method: get
          cors: true
      - http:
          path: helloTest
          method: post
          cors: true
